require('dotenv').config();
const express=require('express');
const fetch=require('node-fetch');
const path=require('path');
const app=express(); app.use(express.json());
const PORT=process.env.PORT||3000;
const SUPA=(process.env.SUPABASE_URL||'').replace(/\/+$/,'');
const SUPA_KEY=process.env.SUPABASE_ANON_KEY||process.env.SUPABASE_PUBLISHABLE_KEY||'';
const GRIZZLY='https://api.grizzlysms.com/stubs/handler_api.php';
const DEF={admin_password:process.env.ADMIN_PASSWORD||'123456',access_password:process.env.ACCESS_PASSWORD||'123456',grizzly_api_key:process.env.GRIZZLY_API_KEY||'',service:'lf',country:'6',country_name:'Indonesia',dial:'+62',cost:0.01};
const COUNTRY={'6':['Indonesia','+62','🇮🇩'],'10':['Vietnam','+84','🇻🇳'],'16':['United Kingdom','+44','🇬🇧'],'36':['Canada','+1','🇨🇦'],'52':['Thailand','+66','🇹🇭'],'73':['France','+33','🇫🇷'],'182':['Japan','+81','🇯🇵'],'187':['United States','+1','🇺🇸'],'22':['India','+91','🇮🇳'],'4':['Philippines','+63','🇵🇭'],'7':['Malaysia','+60','🇲🇾'],'33':['Colombia','+57','🇨🇴'],'30':['Brazil','+55','🇧🇷']};
function host(req){return String((req.headers['x-forwarded-host']||req.headers.host||'default')).split(',')[0].split(':')[0].replace(/^www\./i,'').toLowerCase()||'default'}
function need(){if(!SUPA||!SUPA_KEY)throw Error('MISSING_SUPABASE_ENV')}
async function sb(url,opt={}){need();let r=await fetch(`${SUPA}/rest/v1/${url}`,{...opt,headers:{apikey:SUPA_KEY,Authorization:`Bearer ${SUPA_KEY}`,'Content-Type':'application/json',Prefer:opt.prefer||'',...(opt.headers||{})}});let t=await r.text();let d;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw Error(typeof d==='string'?d:JSON.stringify(d));return d}
async function cfg(domain){let rows=await sb(`domain_configs?domain=eq.${encodeURIComponent(domain)}&select=*`); if(rows&&rows[0])return {...DEF,...rows[0]}; let c={domain,...DEF}; await sb('domain_configs',{method:'POST',body:JSON.stringify(c),prefer:'return=minimal'}); return c}
async function save(domain,c){await sb('domain_configs',{method:'POST',body:JSON.stringify({domain,admin_password:c.admin_password,access_password:c.access_password,grizzly_api_key:c.grizzly_api_key,service:c.service,country:c.country,country_name:c.country_name,dial:c.dial,cost:Number(c.cost||0),updated_at:new Date().toISOString()}),prefer:'resolution=merge-duplicates,return=minimal'})}
async function griz(c,params){if(!c.grizzly_api_key)throw Error('MISSING_GRIZZLY_API_KEY');let u=new URL(GRIZZLY);u.searchParams.set('api_key',c.grizzly_api_key);Object.entries(params).forEach(([k,v])=>{if(v!==undefined&&v!==null&&v!=='')u.searchParams.set(k,String(v))});let r=await fetch(u);return (await r.text()).trim()}
function mask(k){return !k?'chưa có':(k.length>8?k.slice(0,4)+'...'+k.slice(-4):'********')}
async function access(req,res,next){try{let d=host(req),c=await cfg(d);if(String(req.headers['x-access-password']||'')!==c.access_password)return res.status(403).json({ok:false,error:'ACCESS_PASSWORD_INVALID'});req.domainKey=d;req.c=c;next()}catch(e){res.status(500).json({ok:false,error:e.message})}}
async function admin(req,res,next){try{let d=host(req),c=await cfg(d);if(String(req.headers['x-admin-password']||'')!==c.admin_password)return res.status(403).json({ok:false,error:'ADMIN_PASSWORD_INVALID'});req.domainKey=d;req.c=c;next()}catch(e){res.status(500).json({ok:false,error:e.message})}}
app.use(express.static(path.join(__dirname,'public')));
app.get('/api/health',(req,res)=>res.json({ok:true,domain:host(req),supabase:Boolean(SUPA&&SUPA_KEY)}));
app.post('/api/auth/check-access',access,(req,res)=>res.json({ok:true,domain:req.domainKey}));
app.get('/api/app/config',access,(req,res)=>{let c=req.c;res.json({ok:true,domain:req.domainKey,selected:{service:c.service,country:c.country,name:c.country_name,dial:c.dial,cost:c.cost}})});
app.get('/api/balance',access,async(req,res)=>{try{let raw=await griz(req.c,{action:'getBalance'});let balance=raw.startsWith('ACCESS_BALANCE:')?raw.split(':')[1]:raw;res.json({ok:true,balance,raw})}catch(e){res.json({ok:false,error:e.message})}});
app.post('/api/admin/login',admin,(req,res)=>{let c=req.c;res.json({ok:true,domain:req.domainKey,settings:{keyMasked:mask(c.grizzly_api_key),service:c.service,country:c.country,name:c.country_name,dial:c.dial,cost:c.cost}})});
app.get('/api/admin/prices',admin,async(req,res)=>{try{let data=JSON.parse(await griz(req.c,{action:'getPrices',service:'lf'}));let rows=[];for(let [country,services] of Object.entries(data||{})){if(!services||!services.lf)continue;let it=services.lf,count=Number(it.count||0),cost=Number(it.cost||0);if(count<=0)continue;let info=COUNTRY[country]||['Country '+country,'+','🌍'];rows.push({country,service:'lf',name:info[0],dial:info[1],flag:info[2],count,cost})}rows.sort((a,b)=>a.cost===b.cost?b.count-a.count:a.cost-b.cost);res.json({ok:true,prices:rows})}catch(e){res.status(500).json({ok:false,error:e.message})}});
app.post('/api/admin/save',admin,async(req,res)=>{try{let c={...req.c};let ap=String(req.body.adminPassword||'').trim(),xp=String(req.body.accessPassword||'').trim(),key=String(req.body.apiKey||'').trim();if(ap&&ap.length<4)return res.json({ok:false,error:'Mật khẩu admin quá ngắn'});if(xp&&xp.length<4)return res.json({ok:false,error:'Mật khẩu truy cập quá ngắn'});if(ap)c.admin_password=ap;if(xp)c.access_password=xp;if(key)c.grizzly_api_key=key;if(req.body.country){c.service='lf';c.country=String(req.body.country);c.country_name=String(req.body.name||c.country_name);c.dial=String(req.body.dial||c.dial);c.cost=Number(req.body.cost||0)}await save(req.domainKey,c);res.json({ok:true,settings:{keyMasked:mask(c.grizzly_api_key),service:c.service,country:c.country,name:c.country_name,dial:c.dial,cost:c.cost}})}catch(e){res.status(500).json({ok:false,error:e.message})}});
app.post('/api/rent',access,async(req,res)=>{try{let c=req.c,raw=await griz(c,{action:'getNumber',service:c.service,country:c.country});if(raw.startsWith('ACCESS_NUMBER:')){let[,id,phone]=raw.split(':');return res.json({ok:true,id,phone,selected:{name:c.country_name,dial:c.dial,cost:c.cost}})}res.json({ok:false,error:raw})}catch(e){res.status(500).json({ok:false,error:e.message})}});
app.get('/api/status',access,async(req,res)=>{try{let id=String(req.query.id||'');if(!id)return res.status(400).json({ok:false,error:'MISSING_ID'});let raw=await griz(req.c,{action:'getStatus',id});if(raw.startsWith('STATUS_OK:'))return res.json({ok:true,code:raw.split(':').slice(1).join(':')});res.json({ok:true,status:'waiting',raw})}catch(e){res.status(500).json({ok:false,error:e.message})}});
app.post('/api/cancel',access,async(req,res)=>{try{let id=String(req.body.id||'');if(!id)return res.status(400).json({ok:false,error:'MISSING_ID'});let raw=await griz(req.c,{action:'setStatus',status:'8',id});res.json({ok:true,raw})}catch(e){res.status(500).json({ok:false,error:e.message})}});
app.listen(PORT,()=>console.log('OTP Supabase tool running on port '+PORT));
